#!/usr/bin/env bash
# Vendor the Toradex manifest tree into this repo's root at a pinned revision.
#
# WHY: `repo`'s <include name="..."> resolves relative to the manifest-repo ROOT,
# so upstream's tree (torizon/, common-torizon/, bsp/, base/, tezi/, ...) must live
# at our root for our torizon-ab/<vendor>/<channel>.xml includes to work. This
# script copies upstream's tracked files to the root and records the exact SHA, so
# a checkout of THIS repo is reproducible and the upstream bump is one commit.
#
# Our own files (torizon-ab/, scripts/, README.md, UPSTREAM.env, .gitignore) are
# never touched.
#
# Usage:
#   scripts/update-upstream.sh                 # use rev from UPSTREAM.env
#   scripts/update-upstream.sh <git-rev>       # pin a new rev (updates UPSTREAM.env)
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$here"

# shellcheck disable=SC1091
[ -f UPSTREAM.env ] && . ./UPSTREAM.env
UPSTREAM_URL="${UPSTREAM_URL:-https://git.toradex.com/toradex-manifest.git}"
UPSTREAM_BRANCH="${UPSTREAM_BRANCH:-scarthgap-7.x.y}"   # TODO: confirm the Torizon branch we build
REV="${1:-${UPSTREAM_REV:-}}"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

echo ">> cloning $UPSTREAM_URL ($UPSTREAM_BRANCH)"
git clone --quiet --branch "$UPSTREAM_BRANCH" "$UPSTREAM_URL" "$tmp/up"
if [ -n "$REV" ]; then
  git -C "$tmp/up" checkout --quiet "$REV"
fi
SHA="$(git -C "$tmp/up" rev-parse HEAD)"
echo ">> upstream at $SHA"

# Our own files — never overwritten or deleted by the sync. Upstream also ships a
# root README.md (and .gitlab-ci.yml etc.); excluding OURS keeps ours authoritative.
OURS=(torizon-ab scripts README.md UPSTREAM.env .gitignore .git)

# Stage the pinned upstream tree, then mirror it onto our root while preserving
# OURS. rsync --delete removes upstream files that disappeared between revs;
# per-path excludes make it never touch our files (dotfiles included).
mkdir -p "$tmp/stage"
git -C "$tmp/up" archive HEAD | tar -x -C "$tmp/stage"

excludes=()
for o in "${OURS[@]}"; do excludes+=(--exclude "/$o"); done
rsync -a --delete "${excludes[@]}" "$tmp/stage"/ "$here"/

# Record the pin.
cat > UPSTREAM.env <<EOF
# Pinned upstream manifest — regenerated by scripts/update-upstream.sh <rev>.
#
# scarthgap-7.x.y = Torizon OS 7.x (Scarthgap). master will become the next
# release (wrynose / Torizon OS 8.x) — do NOT track it here yet.
# Release channel stays on a pinned REV; the nightly channel re-vendors at tip.
UPSTREAM_URL="$UPSTREAM_URL"
UPSTREAM_BRANCH="$UPSTREAM_BRANCH"
UPSTREAM_REV="$SHA"
EOF

echo ">> vendored upstream @ $SHA"
echo ">> review 'git status', then commit:  git commit -am 'sync upstream @ ${SHA:0:12}'"
